spring.application.name=SpringDataJPA6
spring.datasource.url=jdbc:mysql://localhost:3306/hibernate
spring.datasource.username=root
spring.datasource.password=sanjai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
